### ISSUE TITLE
Recognize trends in measures where there're more than one year in data

### ISSUE THREAD

**Issue by cnavarreteliz** [cnavarreteliz/vizbuilder#13]
Use these variations and add new color options.
Ex. % Growth Salary by Industry Sector period 2009 - 2016

**Comment by cnavarreteliz** [comment]
My idea is show information about main increases in left panel

**Comment by cnavarreteliz** [comment]
I want to calculate a "prediction" for next year. For example, in JobsKSA data are available until 2016 and I hope get predictions for 2017.

**Comment by davelandry** [comment]
@cnavarreteliz I like this idea, but let's only focus on this when we have the vizbuilder in a more stable state. we need to iterate on the design interaction before pursuing more data analysis

**Comment by cnavarreteliz** [comment]
Ok! I'll focus in other issues ^^
