### ISSUE TITLE
add old filter/cuts and appearance options to the bottom of the sidebar

### ISSUE THREAD

**Issue by davelandry** [cnavarreteliz/vizbuilder#15]

**Comment by davelandry** [comment]
@cnavarreteliz please add a comment here containing either a text list or screenshots of what was available in the old panel, and we can work together to consolidate the list

**Comment by cnavarreteliz** [comment]
@davelandry it had filter front-end options that recognized data loaded and this got create custom filters. For example, if was selected "Salary Sum", you can filter by Salary Sum without need create a cut. This was more quickly than cut option. Front-end Filter only work with data selected in the search.

Also had a preliminar version of Cuts, but with Francisco were talking about show a modal for select cut options. 

Other element in the old panel was a "Assistant", the idea was generate recommendations, but we have to iterate it.

**Comment by davelandry** [comment]
@cnavarreteliz I'm not understanding what you are saying. can you post a screenshot of what the panels used to look like?

**Comment by davelandry** [comment]
closing this in favor of #40
