### ISSUE TITLE
calculate yearly growth on the front-end

### ISSUE THREAD

**Issue by davelandry** [cnavarreteliz/vizbuilder#16]

**Comment by cnavarreteliz** [comment]
![captura de pantalla 2017-09-22 a la s 16 33 40](https://user-images.githubusercontent.com/5233593/30761224-de13403c-9fb3-11e7-9d47-4f5d6d760b66.png)

I want to set colorScale center in zero, and I must fix a few issues with WebGL contexts in DeeplearnJS

**Comment by davelandry** [comment]
@cnavarreteliz what are using WebGL and DeeplearnJS for? is that overkill for calculating growth?

**Comment by cnavarreteliz** [comment]
Principally I use deeplearnjs in division by tensors, is more quickly.
