### ISSUE TITLE
add interface to calculate buckets

### ISSUE THREAD

**Issue by davelandry** [cnavarreteliz/vizbuilder#17]
I'm thinking of something like:

```
Group into <X> buckets
```

where `<X>` is a dropdown of numbers 1-10.

**Comment by cnavarreteliz** [comment]
![captura de pantalla 2017-09-27 a la s 00 09 10](https://user-images.githubusercontent.com/5233593/30894127-3fd4a376-a318-11e7-8e03-ced397ed8f39.png)

**Comment by cnavarreteliz** [comment]
In ages, I think that is better something like:

    Interval of <x> years

**Comment by davelandry** [comment]
I agree, specifically of the different `<x>` values are determined from the range of years available in the data.

For example, if there are only 50 years of data available, the user should not be able to group the data into anything larger than 25 year buckets.

**Comment by davelandry** [comment]
Great job with this @cnavarreteliz!
