### ISSUE TITLE
group lowest categories in treemap

### ISSUE THREAD

**Issue by cnavarreteliz** [cnavarreteliz/vizbuilder#18]
In some dimensions, there are many categories (more than 50) and this situation spoil Treemap / Donut charts.

My idea is group "alpha" percent of the lowest categories in "Other".

**Comment by cnavarreteliz** [comment]
I have some dudes about how to implement this idea, better tomorrow in Sprint i try to explain my algorithm and I receive feedback

**Comment by cnavarreteliz** [comment]
![captura de pantalla 2017-09-27 a la s 12 23 56](https://user-images.githubusercontent.com/5233593/30922238-ee9f45d0-a37e-11e7-9a91-d36c8a87c82f.png)

I grouped 5% lowest categories, but I think that is now the better is stop this idea and iterate design and if is important by the final user. I have the impression that too much categories difficult the interpretation.

In this example, I expected that "Other categories" was in bottom-right position.

**Comment by davelandry** [comment]
Love this idea, and great job implementing it!
