### ISSUE TITLE
"supercube" 

### ISSUE THREAD

**Issue by cnavarreteliz** [cnavarreteliz/vizbuilder#19]
I think that is a good option merge similar dimensions of all cubes and create dropdown with different measures.

    Cube 1 { Age, Age bucket, Occupation }
    Cube 2 { Occupation, Industry Group }
    Cube 3 { Age, Industry Group }

    Supercube { Age, Age bucket, Occupation, Industry Group }

And and instead of select random cube in Vizbuilder, select supercube!

**Comment by davelandry** [comment]
@cnavarreteliz can you give me an example of how the current interface would change?

**Comment by cnavarreteliz** [comment]
The idea is that interfaz doesn't change. I'll go iterating the idea, and I'll show you my progress. I think that is a good idea for to implement.

**Comment by cnavarreteliz** [comment]
@davelandry I've was thinking the idea. Usually, the search is -> Select cube, and after select dimension. But dimensions with same name are in more than one cube (Ex. Age, Gender, Occupation, etc)

My idea is select first a dimension, and after select a specific cube with more natural language.

I want to see -> Occupations
In -> { Employee Records , Occupation Flow }

**Comment by davelandry** [comment]
@cnavarreteliz I'm still confused, where does the cube and dimension selection happen right now?

<img width="283" alt="screen shot 2017-10-02 at 2 57 47 pm" src="https://user-images.githubusercontent.com/1847581/31094163-2b6fc208-a782-11e7-85a7-05b4a64efa6f.png">

**Comment by davelandry** [comment]
After talking with @cnavarreteliz in Slack, we are going to pause development on this feature.
