### ISSUE TITLE
enable d3plus timeline

### ISSUE THREAD

**Issue by davelandry** [cnavarreteliz/vizbuilder#22]
should just require setting the `"time"` config to equal the time key in the data

**Comment by cnavarreteliz** [comment]
works fine! but I have a little question about how can I selected all years, `"time" `config only select last year by default

**Comment by cnavarreteliz** [comment]
I solved it!

**Comment by davelandry** [comment]
@cnavarreteliz the last year should be the default selected year. In most cases, like in Tree Maps, it is better to only show the latest year at first instead of all years.

The logic should be:
 - if the visualization has an X or Y axis set to year, show all years
 - otherwise, show latest year
