### ISSUE TITLE
add dataset dropdown

### ISSUE THREAD

**Issue by davelandry** [cnavarreteliz/vizbuilder#23]
Currently, a random cube is selected for measures. The user flow should be:

Dataset: [ dataset dropdown ]
I want to see:  [ dimension dropdown ]
Sized by: [ measure dropdown ]

**Comment by cnavarreteliz** [comment]
![captura de pantalla 2017-10-02 a la s 17 15 01](https://user-images.githubusercontent.com/5233593/31097332-4f27dcfe-a795-11e7-8fc5-6b0427f595a5.png)

^^
