### ISSUE TITLE
remove first/last years from consts.js

### ISSUE THREAD

**Issue by davelandry** [cnavarreteliz/vizbuilder#24]
I see that there are 2 static variables defined in `app/helpers/consts.js` for `FIRST_YEAR` and `LAST_YEAR`. Where are these currently being used?

If they are still needed, we should talk with the API team to find a way to get them through the API.

If they are no longer needed, we should remove them from the codebase.

**Comment by cnavarreteliz** [comment]
I revised it and never used them. I think that in a begin I defined because in `CNY-Vitals` was like base.

**Comment by davelandry** [comment]
@cnavarreteliz awesome, can you remove them from the `consts.js` file and close this issue?
