### ISSUE TITLE
set up additional route using DataChile cube

### ISSUE THREAD

**Issue by davelandry** [cnavarreteliz/vizbuilder#25]
we should have:
```
http://vizbuilder.datawheel.us/ksa
http://vizbuilder.datawheel.us/chile
```

This will help us test how well the vizbuilder is generalized for different datasets. Here is the URL for DataChile: https://chilecube.datawheel.us/

**Comment by cnavarreteliz** [comment]
404 error :(

**Comment by frabarz** [comment]
First attempt in a84115cc032d66eb2d26a284c165c630c1db3adc

**Comment by davelandry** [comment]
Awesome work @frabarz! When you feel it's stable, you can close this issue.
