### ISSUE TITLE
add logic to determine a measure's type

### ISSUE THREAD

**Issue by cnavarreteliz** [cnavarreteliz/vizbuilder#26]
@davelandry I believe that it's important set a protocol in measures. For example, in every measure object put `type` key.

```
{
"name": "Age Average",
"type": "average"
},
{
"name": "Age AVG",
"type": "average"
},
{
"name": "Salary Sum",
"type": "sum"
}
```
With that type key, we can recommend better charts :)

This protocol can be applied if a dimension is a timeDimension (in JobsKSA there's this classification but in chilecube doesn't)

**Comment by cnavarreteliz** [comment]
For now, I can work in a regex that recognize measure's type! :)

**Comment by davelandry** [comment]
@cnavarreteliz we should require the cubes to send all measures types, and if they don't have a type, just fall back to `sum` if the regex cannot determine the type.

@jazzido any chance we can get "type" fields for dimensions?

**Comment by jazzido** [comment]
@davelandry dimensions currently expose a `type` field:

![image](https://user-images.githubusercontent.com/27584/31155147-6755712c-a882-11e7-9f13-fde30bf9e854.png)

WRT measure types, as we talked earlier today, I can patch `mondrian-rest` so it exposes the type of aggregation used by each measure. However, some of them won't use "trivial" aggregators such as `avg`, `sum` or `count`.

@cnavarreteliz @frabarz can you expand on _why_ you need to know the type of aggregation of a measure?

**Comment by jspeis** [comment]
@manuel @cnavarreteliz I assume the reason is related to suggesting visualizations. I.e we might not want to size a tree map by averages or growth rates. So the simple cases of sum/count/avg are straight forward, but for things like calculated growth rates which might rely on a formula might be nice to have a way to indicate what the measure represents to help better suggest vizs

**Comment by cnavarreteliz** [comment]
My idea is exactly what @jspeis says. For example, if a person wants to create a chart with "Average Age" measure, treemap is not best option, or if tries to view a treemap, between the measure options for the size should be no type of aggregation with average.

I was thinking in use Regex in frontend for check this, but the name in format between measures cubes are differents (Ie in Datachile, an Average is represented with AVG, and in KSA Jobs with "Average") and is not scalable.

Thanks by your time @jazzido

**Comment by jazzido** [comment]
Thanks! OK, I'll implement this this week and release a new version of `mondrian-rest`.
@jspeis i'll let you know so you can update KSA cubes server with the new version.

**Comment by jazzido** [comment]
Hi @cnavarreteliz,

I've just released version 0.7.4 of `mondrian-rest`. It implements the requested feature: now, measures report the aggregator used to calculate them. Along with that, there's a new revision of `mondrian-rest-client` (you should update its entry in your `package.json` to rev `b782d99ce94ff56914eed3c6b9004f600c6f16f0`).

@jspeis (or @hwchen) when you have the chance, update the KSA cubes server to `mondrian-rest 0.7.4` so the guys can use this new feature.

Have fun!

**Comment by hwchen** [comment]
ksa has been updated, let me know if there's any issues.

**Comment by davelandry** [comment]
Closing this issue, as cubes will not be required to pass an annotation of their type if they want to use those features in the viz builder.
