### ISSUE TITLE
do not destroy previous visualization when querying for new data

### ISSUE THREAD

**Issue by davelandry** [cnavarreteliz/vizbuilder#36]
currently, changing a toggle causes the visualization to completely clear. it should stay with the previous data until the new data is ready

**Comment by cnavarreteliz** [comment]
@frabarz close it if you think this is solved.

**Comment by davelandry** [comment]
@frabarz can this be closed? looks implemented to me

**Comment by frabarz** [comment]
Yeah, I left it open in case some bug appeared.
