### ISSUE TITLE
set up OEC cube

### ISSUE THREAD

**Issue by davelandry** [cnavarreteliz/vizbuilder#37]
@cnavarreteliz, let's meet with @alexandersimoes and @hwchen about getting the data and setting it up

**Comment by cnavarreteliz** [comment]
I'm working setting cube in [http://oec-cube.datawheel.us/cubes](url)

**Comment by davelandry** [comment]
@cnavarreteliz I'm unable to load any of the OEC visualizations 😢

**Comment by cnavarreteliz** [comment]
@davelandry the problem is that @frabarz when was working in filters broke some components, but now we are working in fix all the issues, because no cube is working :/
