### ISSUE TITLE
more visible loading indicator

### ISSUE THREAD

**Issue by davelandry** [cnavarreteliz/vizbuilder#38]
the small blue line at the top of the screen isn't very visible. I think a better visual indicator would be a `<div>` that covers the entire visualization with a progress bar in the center. take a look at the Blueprint progress slider: http://blueprintjs.com/docs/#core/components/progress/progress-bar

**Comment by frabarz** [comment]
0d66576290e3dcab7b14ed2c2eefc007cec463b9 should solve this, but I can't close it yet because there's still room for improvements.

**Comment by davelandry** [comment]
@frabarz there should definitely be some text above the loading bar that says "Loading..."

would it be possible to display the chart name, like "Loading Age by Gender"?

**Comment by frabarz** [comment]
Added on 802debbd7b7dea0b4efceb9eba524f468e83c977, it's also working in the demo.
For now it's showing "<drilldown> by <measure>", should I add the cube name?

**Comment by davelandry** [comment]
The text currently says:

> Loading *\<dimension> by \<measure>*

Change it to:

> Loading \<cube> by \<dimension>

This matches the title above the chart and also removes the italics around the title.

**Comment by davelandry** [comment]
@frabarz I believe this has been completed, time to close this issue?
