### ISSUE TITLE
begin defining a custom vizbuilder cube annotation

### ISSUE THREAD

**Issue by davelandry** [cnavarreteliz/vizbuilder#41]
@cnavarreteliz we should never be trying to detect anything on a measure based on it's name or content. Everything the viz-builder does should be determined from annotations. As discussed on the call, let's define a pre-defined annotation object that we will document and show to the @jazzido and @hwchen. For now, I am thinking something like this:

```json
"annotations": {
  "vizbuilder": {
    "type": "AGE"
  }
}
```

And then, we would have a list of pre-defined values for each key:

### type
* `"AGE"`
* `"GENDER"`

@cnavarreteliz please post any additional ideas you have here, and then update the `README.md` file with the code example and pre-defined lists.

**Comment by cnavarreteliz** [comment]
I'm iterating this idea here:

[Dimension types](https://github.com/cnavarreteliz/vizbuilder/wiki/Dimension-types)
[Measure types](https://github.com/cnavarreteliz/vizbuilder/wiki/Measure-types)
