### ISSUE TITLE
data from chart and "View data" option are different

### ISSUE THREAD

**Issue by cnavarreteliz** [cnavarreteliz/vizbuilder#43]
![captura de pantalla 2017-10-31 a la s 15 05 02](https://user-images.githubusercontent.com/5233593/32242009-696adc84-be50-11e7-8bb1-3f1052982c7f.png)

**Comment by cnavarreteliz** [comment]
Data are the same, the problem is that in "View Data" option you can see data available for all years. I think that I can add a "+" option for to see more details by year, and only show "Total". 

Or the other option is always show last year @davelandry.
What's the best option?

**Comment by davelandry** [comment]
@cnavarreteliz why not make the chart split by years? I thought we were making a timeline for any dataset with a time variable?

**Comment by davelandry** [comment]
@cnavarreteliz here is an example of how to get the selected time from the d3plus timeline: http://jsfiddle.net/5Lp5kk0x/

**Comment by cnavarreteliz** [comment]
I'll close this because is solved :)
