### ISSUE TITLE
problem in axis BarChart using AVG measures

### ISSUE THREAD

**Issue by cnavarreteliz** [cnavarreteliz/vizbuilder#44]
![captura de pantalla 2017-10-31 a la s 15 05 10](https://user-images.githubusercontent.com/5233593/32242063-9130145a-be50-11e7-83ed-cf6ac8c0f796.png)

**Comment by cnavarreteliz** [comment]
I fixed this using `{aggs: mean}` when `measure.type` is `AVG`.

**Comment by davelandry** [comment]
@cnavarreteliz if this issue is resolved, please close it!
