### ISSUE TITLE
persistent URLs

### ISSUE THREAD

**Issue by davelandry** [cnavarreteliz/vizbuilder#45]
Whenever a setting in the viz-builder is changed, we should update the URL query parameters with the new settings so that if the page is reloaded, the settings persist.

Here's an example of how we did in on the Map page in Data Africa: https://github.com/data-africa/data-africa-site/blob/master/app/pages/Map.jsx#L183

### Steps
- [x] dataset in URL (@frabarz)
- [ ] standardize viz reducer names to match chart types (@cnavarreteliz)
- [ ] get viz styles into the URL (@frabarz)

**Comment by frabarz** [comment]
This will remain open because we need to define the elements that need to be on the permalink, depending on the chart type.
