### ISSUE TITLE
change data popup icon

### ISSUE THREAD

**Issue by davelandry** [cnavarreteliz/vizbuilder#52]
<img width="765" alt="screen shot 2017-11-13 at 1 21 10 pm" src="https://user-images.githubusercontent.com/1847581/32742152-84e5ccaa-c876-11e7-8e30-4188720cacd5.png">

This shouldn't be an inbox icon, change it to match the "View Data" button's "pt-icon-th"

**Comment by cnavarreteliz** [comment]
Closed with [`50e9f11`](https://github.com/cnavarreteliz/vizbuilder/commit/50e9f119b17e86d11a4a47b3da42afb18cb94bba)
