### ISSUE TITLE
empty "value" column in CSV downloads

### ISSUE THREAD

**Issue by davelandry** [cnavarreteliz/vizbuilder#54]
the CSV downloads are giving me an extra "value" column that is empty:

<img width="381" alt="screen shot 2017-11-13 at 1 32 07 pm" src="https://user-images.githubusercontent.com/1847581/32742347-21c78d42-c877-11e7-91d5-ad73add6ee8e.png">

**Comment by cnavarreteliz** [comment]
Closed with [`be96fab`](https://github.com/cnavarreteliz/vizbuilder/commit/be96fab0a3ba863fa0c9f1a91978c0f7d7e4739e)

**Comment by davelandry** [comment]
@cnavarreteliz I'm still seeing this on the live site, has this change been pushed?
