### ISSUE TITLE
title dropdown is broken

### ISSUE THREAD

**Issue by davelandry** [cnavarreteliz/vizbuilder#55]
<img width="667" alt="screen shot 2017-11-13 at 1 34 38 pm" src="https://user-images.githubusercontent.com/1847581/32742440-70815eea-c877-11e7-9bd9-d6d06c748708.png">

**Comment by frabarz** [comment]
I tried to [replicate the view](http://vizbuilder.datawheel.us/chile?cb=bsm7e&dd=9A7Hy&ms=1YyGxJ) and the treemap is inverted (bigger elements on the right side)
Is that an option?

**Comment by cnavarreteliz** [comment]
@frabarz happen because values in measure are negatives. @davelandry maybe if there is one negative value the visualization doesn't must be a Treemap and could be an option use a .some() function that check if some value is negative.

**Comment by davelandry** [comment]
@cnavarreteliz should we just filter out all negative values before drawing the Treemap?
