### ISSUE TITLE
use blueprint icons for chart types

### ISSUE THREAD

**Issue by davelandry** [cnavarreteliz/vizbuilder#62]
<img width="280" alt="screen shot 2017-11-13 at 1 50 06 pm" src="https://user-images.githubusercontent.com/1847581/32743154-9ca4b0d8-c879-11e7-881c-154483e05152.png">

The charts should use blueprint icons as span elements, for example:

```jsx
<div className="select-option current" title={props.value.nllabel}>
  <Icon iconName={props.value.icon} />
  <span className="value">{props.value.nllabel}</span>
  <Icon iconName="double-caret-vertical" />
</div>
```

The icons used should be the following:
* Tree Map: `control`
* Donut: `doughnut-chart`
* Pie: `pie-chart`
* Line: `timeline-line-chart`
* Bubble: `heatmap`
* Stacked: `timeline-area-chart`
* Bar: `timeline-bar-chart`
* Table: `th`

Once this change is made, please remove any lingering SVG assets of the previous icons from the repository.

**Comment by cnavarreteliz** [comment]
Closed with [`d6d01c9`](https://github.com/cnavarreteliz/vizbuilder/commit/d6d01c93cd2cc81f40017bdf0a6f63553b6b12af)
